# Generated by Django 4.1.3 on 2022-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makanan',
            old_name='Kantin',
            new_name='kantin',
        ),
        migrations.AlterField(
            model_name='makanan',
            name='gambar',
            field=models.ImageField(upload_to='makanan/images/'),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='tersedia',
            field=models.CharField(choices=[('1', 'Tersedia'), ('2', 'Tidak tersedia')], max_length=1),
        ),
    ]
